### ISSUE TITLE
让docker版可以在config里指定domain是否启用https

### ISSUE THREAD

**Issue by RuoYear** [ssrlive/proxypool#108]
## Description 描述
localconfig会设置为http://127.0.0.1:port
config则只能是https://domain
网页端访问局域网的订阅则会变成IP地址前均为https
是否可以用参数，允许特定地址构造，以支持局域网不带http的访问和订阅？
例如指定目标地址为局域网的：http://192.168.1.1:port

**Comment by fangpsh** [comment]
我简单暴力go-bindata 修改internal/bindata/html 下的资源内容，都改成了http；
这里是一个自用的镜像：
https://hub.docker.com/repository/docker/fangpeishi/pr0xypo0l/general

**Comment by RuoYear** [comment]
@fangpsh 感谢你提供的思路和镜像，这是一个适合临时解决问题的“补丁”😊

**Comment by ssrlive** [comment]
我把打包代碼去掉，解壓出原始檔案，然後你提交一個補丁怎麼樣？ @fangpsh

**Comment by ssrlive** [comment]
我把打包代碼去掉，解壓出原始檔案，然後你在這個基礎上提交一個補丁怎麼樣？ @fangpsh
