### ISSUE TITLE
[BUG]database not save

### ISSUE THREAD

**Issue by jackadam1981** [ssrlive/proxypool#112]
- [x] I'm using the newest release version, and bug isn't solved
  我使用的是最新的release版本，Bug仍未解决
- [x] I've tested on the newest master, and bug isn't solved
  我测试的是最新master分支，Bug仍未解决
- [x] I've searched the issues and there's not a similar one
  我已经查看过其他issue，没有类似的情况

Bug Version出现Bug的版本：v0.x.x  
Environment操作环境：heroku/ubuntu/mac
  
## To Reproduce 复现步骤
我使用docker部署proxypool，并使用postgresql来作为数据库存储。
docker compose文件如下
version: "3.3"

services:

  proxypool:
    container_name: proxypool
    image: lukemin/ssrlive-proxypool
    restart: always
    command: -c /config/config.yaml
    volumes:
      - ./config:/config
    ports:
      - 12580:12580
    depends_on:
      - db
  db:
    image: postgres
    container_name: proxypool_db
    restart: always
    environment:
      POSTGRES_PASSWORD: JymgBuiB8nhCV8BZ5ASt
      POSTGRES_USER: pooluser
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 15432:5432

config.yaml如下：
# your domain
domain: example.com:   # or example.com:9443 for reserve proxy server
port:                 # default 12580

# source list file
source-files:
  # use local file
  - source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# ======= 可选项，留空使用default值  ======= #

#====Postgresql database info ====#
database_url: "postgresql://pooluser:JymgBuiB8nhCV8BZ5ASt@proxypool_db:5432/pooluser"

#==== Interval between each crawling ====#
crawl-interval:             # v0.5.x default 60 (minutes)
#crontime:                  # v0.4.x default 60 (minutes). Deprecated in the newest version
healthcheck-timeout:        # default 5 (seconds)
healthcheck-connection:     # default 500. The number of health check connections simultaneously

#==== Speed test ====#
speedtest: true            # default false. Warning: this will consume large network resources.
speedtest-interval:         # default 720 (min)
speed-timeout:              # default 10 (seconds).
speed-connection:           # v0.7.2 default 5. The number of speed test connections simultaneously
#connection                 # v0.7.1 and beblow

#==== Active proxy speed test ====#
active-interval:            # default 60 (min)
active-frequency:           # default 100 (requests per interval)
active-max-number:          # default 100. If more than this number of active proxies, the extra will be deprecated by speed

#==== Cloudflare api ====#
cf_email: ""
cf_key: ""

开启以后，抓到数据，但是我查看数据库，只有空表proxies
认真翻了一下日志，发现第一次运行，
proxypool     | [0000]  INFO Running image path: /proxypool-src/proxypool
proxypool     | [0000]  WARN database connection info: failed to connect to `host=proxypool_db user=pooluser database=pooluser`: dial error (dial tcp [fc00:0:0:2::2]:5432: connect: connection refused)
proxypool     |                 Use cache to store proxies

什么都不修改，down up，再次运行
proxypool     | [0000]  INFO Running image path: /proxypool-src/proxypool
proxypool     | [0000]  INFO database: successfully connected to: postgres
proxypool     | [0001]  INFO Do the first crawl...

我已经设置了    
depends_on:
      - db
 数据库启动后才启动proxypool的。
是数据库初始化的问题么？

**Comment by ssrlive** [comment]
沒有關注數據庫那一塊。
