### ISSUE TITLE
[BUG]go get cannot find module for path crypto/ed25519

### ISSUE THREAD

**Issue by lanhebe** [ssrlive/proxypool#115]
按照源码编译步骤，当执行go get命令后报错，
root@localhost:~/proxypool/proxypool# go get
build github.com/ssrlive/proxypool: cannot find module for path crypto/ed25519

请问以上是缺少什么模块，麻烦补充并执教，谢谢！

**Comment by ssrlive** [comment]
執行 `go get -u` 命令以後還有問題嗎？

**Comment by lanhebe** [comment]
執行 go get -u 命令以後還有問題，go get: error loading module requirements

**Comment by sdjames64157** [comment]
更新下go版本，低于1.13会报这个错误
