### ISSUE TITLE
wget https://github.com/ssrlive/proxypool/releases/download/v0.6.1/proxypool-linux-amd64-v0.6.1.gz

### ISSUE THREAD

**Issue by wangh00** [ssrlive/proxypool#167]
wget https://github.com/ssrlive/proxypool/releases/download/v0.6.1/proxypool-linux-amd64-v0.6.1.gz
--2024-03-07 02:13:30--  https://github.com/ssrlive/proxypool/releases/download/v0.6.1/proxypool-linux-amd64-v0.6.1.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-07 02:13:30 ERROR 404: Not Found.
**没有找到该文件，咋办**

**Comment by ssrlive** [comment]
本分支没提供二进制啊,全是源码.
