### ISSUE TITLE
请问能否支持爬取白嫖机场节点

### ISSUE THREAD

**Issue by bywhat123** [ssrlive/proxypool#205]
## Description 描述
https://github.com/wzdnzd/aggregator 大佬能不能支持自动爬取白嫖机场的节点，就像这个项目一样，能从机场列表里自动注册购买白嫖套餐

**Comment by ssrlive** [comment]
我都一年多沒動過這個了，完全提不起興趣，連 Golang 都忘了，歡迎你貢獻代碼。

**Comment by bywhat123** [comment]
> 我都一年多沒動過這個了，完全提不起興趣，連 Golang 都忘了，歡迎你貢獻代碼。

那就算了 我也是小白 多谢大佬
