### ISSUE TITLE
关于定时抓取时无法读取配置文件的问题

### ISSUE THREAD

**Issue by ICEY1W32** [ssrlive/proxypool#44]
最初是在查看docker日志时发现的，在运行编译程序时同样出现，日志片段如下：
[0101]  INFO Relay Test ON
        [100.0% DONE]
[0111]  INFO Usablility checking done. Open * to check
[0300] ERROR cron.go: config parse error: read /proxypool-master: is a directory
[0301]  INFO STATISTIC: TGChannel       count=0 url=*

我也尝试过直接从源码运行，但是报错如下：
[0000]  INFO Getter count: 1
                Use cache to store proxies
panic: Asset assets/flags.json can't read by error: error when reading asset assets/flags.json at assets/flags.json: open assets/flags.json: no such file or directory

goroutine 1 [running]:
github.com/ssrlive/proxypool/pkg/geoIp.InitGeoIpDB()
        /proxypool-0.7.6/pkg/geoIp/geoip.go:24 +0x200
main.main()
        /proxypool-0.7.6/main.go:52 +0x2d8
exit status 2

同样环境下Sansui233/proxypool0.7.3版本运行正常

**Comment by ICEY1W32** [comment]
> 它说没找到 assets/flags.json 文件，你把 docker 文件改改，加入复制 assets 文件夹内容的命令后，看看如何？

这个报错只会在从源码运行时出现，docker部署则没有这个问题，而是无法读取配置文件的问题

**Comment by ssrlive** [comment]
編譯以後從二進制文件 proxypool 開始運行，有問題嗎？

**Comment by ICEY1W32** [comment]
> 編譯以後從二進制文件 proxypool 開始運行，有問題嗎？

从docker以及二进制文件运行就会在第二次抓取时出现如下问题：
[0101] INFO Relay Test ON
[100.0% DONE]
[0111] INFO Usablility checking done. Open * to check
[0300] ERROR cron.go: config parse error: read /proxypool-master: is a directory
[0301] INFO STATISTIC: TGChannel count=0 url=*

**Comment by ssrlive** [comment]
也就是說，第一次運行時正常，但第二次運行任務 就崩了？

**Comment by ICEY1W32** [comment]
> 也就是說，第一次運行時正常，但第二次運行任務 就崩了？

嗯，第一次抓取没有问题，设置的抓取间隔时间到后执行第二次抓取时，就会报错，之后会正常检测可用性以及测速，但是节点数量不再增加

**Comment by ssrlive** [comment]
剛纔把代碼和 0.7.3 版本逐行比較了一下，我認爲我沒有改得更壞，就是把配置文件的相對路徑讀取策略改正確了，還有就是把 SSR 節點的篩選邏輯稍微調整，讓它不全然依賴 clash 模塊。
你有時間排查一下問題嗎？

**Comment by ICEY1W32** [comment]
> 刚才把代码和 0.7.3 版本行比较一下，我认为我没有更坏的，就是把配置文件的相对读取策略改了，还有就是 SSR 不同精度的筛选调整了，你有时间排查 问题吗？

您无法复现这个问题吗，我并不会go语言，无法提供太多帮助，短期内实在有心无力

**Comment by ssrlive** [comment]
現在看看好了沒？

https://github.com/ssrlive/proxypool/blob/67ac3280567167a582783f2abc2d440db839127a/config/config.go#L150-L176

**Comment by ssrlive** [comment]
現在應該妥了。

**Comment by ICEY1W32** [comment]
运行正常，问题已解决，非常感谢
