### ISSUE TITLE
節點導出數量異常

### ISSUE THREAD

**Issue by ICEY1W32** [ssrlive/proxypool#45]
proxypool-0.7.7運行結果顯示篩選出1612節點
通過/clash/prroxies導出結果僅約為670個
其中SS-350，Trojan-240，Vmess-80，無SSR節點

相同條件下Sansui233/proxypool-0.7.3篩選出1123個節點
其中SS-329，Trojan-218，Vmess-401，SSR-172

導出結果對比明顯異常，但是日誌記錄正常無報錯

**Comment by ssrlive** [comment]
那些 ssr 借点可用吗？如果不可用，那么我就是对的。我简单粗暴地只是检查了 IP：端口 是否可以访问，如果不能，就直接舍弃了。

https://github.com/ssrlive/proxypool/blob/87fa85d1131bcf71856aa859a0fa5dfd20c22e98/pkg/healthcheck/delaycheck.go#L138-L149

**Comment by ICEY1W32** [comment]
SSR節點TCPing全部可ping通
使用谷歌URL測試，有約一半能連通

我認為問題可能出在節點的導出而不是篩選上，當然這個意見僅供參考

**Comment by ssrlive** [comment]
你能把 ssr 节点较多的那个 URL 共享出来么？我调试一把。现在发出来。我收到后你马上删除。

**Comment by ICEY1W32** [comment]
對比測試時間是早上，部分節點在後來的的篩選中被丟棄，考慮到效果較差，中午就關閉了程式
這是0.7.3的最後匯出結果 https://pastebin.com/Gw4PAn3a 匯出格式為 https://github.com/SagerNet/SagerNet
現時已重啓程式進行篩選，結果會在稍後以clash格式給出

**Comment by ICEY1W32** [comment]
最新的clash格式匯出結果 https://pastebin.com/w22fCXQ6

**Comment by ICEY1W32** [comment]
這是部分vmess節點的匯出結果 https://pastebin.com/VprEaiQH 應該足以用來測試

**Comment by ssrlive** [comment]
你的樣本數據在我這裏是能正常識別的。你那裏還異常嗎？

![image](https://user-images.githubusercontent.com/30760636/172051382-8a9ac8b2-d9fb-456b-9acf-2ae61e84adad.png)

**Comment by ICEY1W32** [comment]
測試clash/proxies的導出數量與日誌顯示符合，沒有見到異常，辛苦了 : )
測試用版本∶
https://github.com/ssrlive/proxypool/commit/7b29f81e0e453738a2524aa1b07e7ba9b7284fc5

**Comment by ICEY1W32** [comment]
剛發現還有一個不太明顯的問題，我猜測您是否關閉了跳過tls驗證功能，導致vmess可用數量明顯變少，trojan可用數量略微變少，您可以用
https://proxies.bihai.cf/clash/proxies 這個節點池做對比測試
我這邊測試結果是∶
最新版∶ss-11/ssr-3/vmess-2/trojan-26
0.7.3版∶ss-10/ssr-0/vmess-23/trojan-32

**Comment by ssrlive** [comment]
代碼爛得一批，許多功能都是恰巧能跑通，稍微一動就行爲怪異，努力排查中。我對 golang 也是完全不懂，靠着多年的 C 經驗忍着噁心找問題。弄完再通知你。

**Comment by ICEY1W32** [comment]
可能還是不做過多的改動，只更新一下clash版本和依賴比較好，現在不少節點池甚至還在用0.5.6版本，為此花費太多精力似乎不太值得，有些問題或許只有重構才能解決
以下抓取源供測試參考∶
https://sspool.herokuapp.com/clash/proxies
https://proxypool.ednovas.xyz/clash/proxies
https://fq.lonxin.net/clash/proxies
https://proxies.bihai.cf/clash/proxies

**Comment by ssrlive** [comment]
現在你看看正常了嗎？

**Comment by ICEY1W32** [comment]
對比測試結果∶
最新版∶ss-25/ssr-4/vmess-10/trojan-33
0.7.3版∶ss-19/ssr-3/vmess-33/trojan-30

結果看來vmess還是有明顯的差距

**Comment by ssrlive** [comment]
很神奇，我的代碼並沒有動過 vmess 協議，我只是 劫福 了 ss/ssr 協議，其它都沒動過。

**Comment by ICEY1W32** [comment]
這就相當奇怪了，我在同樣的環境下用同樣的參數和源測試，0.7.3多出來的節點導入v2ray測試大都可用，說明新版的篩選確實是漏掉了可用節點，到底是哪裡出了問題......

**Comment by ssrlive** [comment]
似乎沒有解析 proxypool 訂閱 url 的 getter ，必須得自己寫。

**Comment by ssrlive** [comment]
加了一個分支 https://github.com/ssrlive/proxypool/tree/main-ref ， 是 嚴格意義上的 Sansui233 version 0.7.3 版本，  你把這個分支檢出來試運行看有沒有問題？

**Comment by ICEY1W32** [comment]
https://github.com/ssrlive/proxypool/tree/main-ref 依赖拉取失败，无法运行....

**Comment by ssrlive** [comment]
再來 剛更新。

**Comment by ICEY1W32** [comment]
vmess筛选数量（三次平均值）
0.7.3版：48
ref分支：46
master：15

**Comment by ssrlive** [comment]
哈哈，氣笑了，這他媽都會不一樣。

**Comment by ICEY1W32** [comment]
等下，我master分支没有拉最新的，等我再做一次

**Comment by ssrlive** [comment]
不重要了，我就在 ref 分支上重新開始，我得支持 ssrot 和 proxypool 自身節點源。

**Comment by ICEY1W32** [comment]
大佬加油，等这阵子忙完了我打算系统的学学，希望下次能帮到更多

**Comment by ssrlive** [comment]
這個提交 https://github.com/ssrlive/proxypool/commit/b619b78556083758556384d58c2a7e77747c80a7 是使用的新版舊版 clash 的分水嶺，我猜測是使用了新版 clash， 所以 vmess 節點數量急劇減少。

**Comment by ICEY1W32** [comment]
我对比了 https://github.com/ssrlive/proxypool/commit/ee3a45c1ed24a9f666b15b87c35cc45a399547d4 和 https://github.com/ssrlive/proxypool/commit/b619b78556083758556384d58c2a7e77747c80a7 这两个提交，前者筛选的vmess数量明显多于后者，确实很有可能是使用了新版clash的问题

**Comment by ssrlive** [comment]
嗯，也許你可以到 clash 開發者那裏提個 issue ，告訴他發生了什麼。

**Comment by ICEY1W32** [comment]
1.5.0到1.10.6跨度太大，不一定是clash的问题，clash用户量巨大，如果clash无法使用大部分vmess，那么这么明显的问题大概率已经有人提issue了，使用次级的1.10.0版本试一下怎么样？

**Comment by ssrlive** [comment]
你可以试着改一下 go.mod 文件，我不想 revert 代码了，都是我依赖机器人自动给出的建议。

**Comment by ssrlive** [comment]
应该是。 就是因为无法后向兼容，我不得不改了模块名。 所以， 为了方便， 你一直使用旧版分叉得了。

**Comment by ICEY1W32** [comment]
1.9.0之后版本好像只是采用了新字段名，可否通过略微修改vmess模块代码，使其兼容新版clash?

**Comment by ssrlive** [comment]
我覺得沒必要苦苦兼容舊代碼，捨棄就捨棄了。再說我對 v2 那些沒興趣，也不知道在哪裏動手改。

**Comment by ICEY1W32** [comment]
我尝试了多个版本的clash并简单查看了其代码，发现旧代码实际只能兼容到clash1.6.0，且不论使用新旧内核都无法兼容新的clash配置文件，所以clash抓取功能目前也是半残废状态......其输出的clash配置也无法兼容1.9.0之后的clash

**Comment by ssrlive** [comment]
沒看懂，你是說，proxypool 的抓取 clash 風格的配置不能兼容 新的 clash 代碼？

**Comment by ssrlive** [comment]
我們之所以在這個抓取項目上投入時間精力，是因爲它可以收集各種類型的節點供各種客戶端使用，而不僅僅是全兼容 clash。

說實話我對 clash 是什麼都沒有一點動力去瞭解。

**Comment by ICEY1W32** [comment]
因为目前clash采用了一种新的字段来描述vmess，把ws-path和ws-headers两个参数整合进了ws-opts这个新参数里面
所以proxypool无法正常抓取并筛选目前普遍采用的新clash配置中的vmess节点
生成的节点列表也无法直接供新版本的clash使用，因为其中的vmess写法不兼容

**Comment by ssrlive** [comment]
你是說這一行？ 

https://github.com/ssrlive/proxypool/blob/a1910f48635ad16dc408dffab61e1dbd84b150ff/pkg/proxy/vmess.go#L29

那怎麼改？

**Comment by ICEY1W32** [comment]
写法只是从'ws-path:/, headers: {Host: 你的主机}'变成了 'ws-opts: {path: /你的路径, headers: {Host: 你的主机}}' 所以我想可能兼容起来应该没有想象中的困难
参见 https://github.com/Fndroid/clash_for_windows_pkg/issues/2588

**Comment by ICEY1W32** [comment]
应该把ws-path和ws-headers参数换path和headers就可以了

**Comment by ICEY1W32** [comment]
应该把这两个参数做个转换就可以了，对vmess节点的处理部分不需要过多更改
我也没什么动力去了解clash，但是无法正常处理vmess节点会降低其至少四分之一的性能
所以还是希望能在不做大改动的范围内想办法去解决

**Comment by ICEY1W32** [comment]
去另外一个库下面留了言，这个issue还是reopen吧

**Comment by ssrlive** [comment]
看看這個分支能不能解決問題 https://github.com/ssrlive/proxypool/tree/WSOpts

**Comment by ICEY1W32** [comment]
我用 https://github.com/ssrlive/proxypool/tree/WSOpts 与0.7.3做了12组以上的对比测试，由于数据波动较大，只能说在置信度85%的区间内，可以判断两个程序结果相同，总体来说WSOpts分支筛选出的节点略少，但是毫无疑问相比于之前的分支有质的提高

**Comment by ssrlive** [comment]
又加了一個功能 vmess.CompatibilityFixes ，現在應該妥了。

**Comment by ICEY1W32** [comment]
https://github.com/ssrlive/proxypool/commit/ce0edfcae6dee33f0250573204bd0cb6d7e41519 结果明显比 https://github.com/ssrlive/proxypool/commit/0f36e13e9c4eeae3dd4c33dac8087fdcb784cb92 更差....

**Comment by ICEY1W32** [comment]
是不是为了兼容旧格式，结果有什么地方冲突了

**Comment by ssrlive** [comment]
對。那就去掉吧。

**Comment by ICEY1W32** [comment]
哦对，这个结果指的是 https://github.com/ssrlive/proxypool/commit/ce0edfcae6dee33f0250573204bd0cb6d7e41519 在使用旧格式作为抓取源的结果，用新格式的话结果差不多

> [ce0edfc](https://github.com/ssrlive/proxypool/commit/ce0edfcae6dee33f0250573204bd0cb6d7e41519) 结果明显比 [0f36e13](https://github.com/ssrlive/proxypool/commit/0f36e13e9c4eeae3dd4c33dac8087fdcb784cb92) 更差....

**Comment by ssrlive** [comment]
那留着？

**Comment by ICEY1W32** [comment]
我觉得这两个参数是否可以为空时直接设置默认值？这种方法兼容旧格式应该不容易产生冲突

**Comment by ssrlive** [comment]
這樣吧，舊格式兼容完以後，直接把這兩個參數置空，絕了後患。

**Comment by ssrlive** [comment]
絕了。

**Comment by ICEY1W32** [comment]
设置默认之后可以兼容旧版配置，终于解决了这个问题.....

**Comment by ssrlive** [comment]
這樣一弄以後，就會在輸出的節點上產生冗餘的信息。

**Comment by ICEY1W32** [comment]
原来如此，那还是删掉比较好吧

**Comment by ssrlive** [comment]
我調查一下， go 語言裏的字符串 string 爲空時，是 nil 還是 "" 。

**Comment by ICEY1W32** [comment]
我发现ws-path默认必须置空，不然会在ws-opts中生成一个ws-path参数，就像这样
"ws-opts":{ws-path":"/"}
奇怪的是，就算置空了，也会出现这种结果
"ws-opts":{},"ws-path":"/"

**Comment by ssrlive** [comment]
剛改了，但 ws-opts 這個東西無論如何都會存在，不知道怎麼改。

**Comment by ICEY1W32** [comment]
ws-opts存在是正常的吧，输出结果中ws-path不应该存在才是

**Comment by ICEY1W32** [comment]
ws-opts存在是正常的吧，输出结果中ws-path不应该存在才是

刚刚有点急弄错了，应该是这样:
ws-path默认必须置空，不然会另外生成一个ws-path参数，就像这样
"ws-opts":{},"ws-path":"设定的默认参数"
奇怪的是，就算置空了，也会有部分节点出现这种结果
"ws-opts":{},"ws-path":"/"

**Comment by ICEY1W32** [comment]
还是置空最好，我测试了一下，在"ws-opts":{}这个参数存在的时候 订阅转换会直接忽略 "ws-path":""参数

**Comment by ssrlive** [comment]
空的 "ws-opts" 也去掉了。

**Comment by ICEY1W32** [comment]
终于能用上了，真不容易
