### ISSUE TITLE
[BUG]panic: time: missing Location in call to Time.In goroutine 8 [running]

### ISSUE THREAD

**Issue by Inkshow** [ssrlive/proxypool#75]
- [x] I'm using the newest release version, and bug isn't solved
  我使用的是最新的release版本，Bug仍未解决
- [x] I've tested on the newest master, and bug isn't solved
  我测试的是最新master分支，Bug仍未解决
- [x] I've searched the issues and there's not a similar one
  我已经查看过其他issue，没有类似的情况

Bug Version出现Bug的版本：v0.7.11  
Environment操作环境：linux
  
## Description 问题描述

在我的路由器上，运行后报错
```
panic: time: missing Location in call to Time.In

goroutine 8 [running]:
time.Time.In(...)
	C:/Program Files/Go/src/time/time.go:1122
github.com/ssrlive/proxypool/internal/app.CrawlGo()
	C:/Users/Initsnow/Downloads/Compressed/proxypool-0.7.11/internal/app/task.go:76 +0x13c0
created by main.main
	C:/Users/Initsnow/Downloads/Compressed/proxypool-0.7.11/main.go:62 +0x468
```
## To Reproduce 复现步骤
新路由3，padavan固件，在Windows用go编译后运行
`./proxypool -c ./config/config.yaml`

**Comment by ssrlive** [comment]
把這一行
https://github.com/ssrlive/proxypool/blob/0a571d057939ce8b832d40e0628402820eede07c/internal/app/task.go#L18
改成
```
var location, _ = time.LoadLocation("America/Pheonix")
```
看看怎麼樣？

**Comment by Inkshow** [comment]
> 把這一行
> 
> https://github.com/ssrlive/proxypool/blob/0a571d057939ce8b832d40e0628402820eede07c/internal/app/task.go#L18
> 
> 
> 改成
> ```
> var location, _ = time.LoadLocation("Asia/Shanghai")
> ```
> 
> 看看怎麼樣？

哦谢谢，但我已经通过这篇文章解决了https://blog.csdn.net/wzb_wzt/article/details/117389245
