### ISSUE TITLE
[BUG]Docker 文件不能下载。

### ISSUE THREAD

**Issue by lukemin** [ssrlive/proxypool#79]
- [ N] I'm using the newest release version, and bug isn't solved
  我使用的是最新的release版本，Bug仍未解决
- [ N] I've tested on the newest master, and bug isn't solved
  我测试的是最新master分支，Bug仍未解决
- [ N] I've searched the issues and there's not a similar one
  我已经查看过其他issue，没有类似的情况

Bug Version出现Bug的版本：v0.x.x  
Environment操作环境：heroku/ubuntu/mac
  
## Description 问题描述
$ docker pull ghcr.io/ssrlive/proxypool:latest 不能下载最新docker

**Comment by ssrlive** [comment]
我對 heroku 和 docker 不熟，也沒時間研究，抱歉。你能幫忙修正嗎？

**Comment by wxyzh** [comment]
需要在dockerfile中添加 go mod tidy

**Comment by ssrlive** [comment]
能改到能用，並提交一個 PR 嗎？ @wxyzh

**Comment by lukemin** [comment]
已提交 PR @ssrlive

**Comment by ssrlive** [comment]
已合併，請測試一下看能不能用。
