### ISSUE TITLE
如何修改网页模板？

### ISSUE THREAD

**Issue by lukemin** [ssrlive/proxypool#84]
如何修改网页模板？
里面有好多的css连接失效了。

**Comment by ssrlive** [comment]
直接改生成的那些 html 文件。
然後 用 https://github.com/ssrlive/proxypool/blob/master/docs/genbindata.sh 工具打包生成 go 源代碼。

**Comment by lukemin** [comment]
go语言不太懂，我现在就想修改一下，
https://cdn.jsdelivr.net/gh/sansui233/proxypool-fe/css/index.css
https://cdn.jsdelivr.net/gh/sansui233/proxypool-fe/css/client/metron-icon.css
到本地，还有就是图片中的连接网址是一个废弃的，能删除或者修改成自定义的最好。
![微信截图_20221010131038](https://user-images.githubusercontent.com/12003375/194802878-b358c4df-7651-4cc6-ba23-e2b5209b4bff.png)
还有就是不知道啥原因，docker生产的版本为0.7.11而不是最新的0.7.12

**Comment by ssrlive** [comment]
那這麼着吧：你把改好的網頁打包發到這裏，我替換上去。改的時候運行着應用，改完刷新網頁看看效果。

**Comment by lukemin** [comment]
我已经找到修改的方法了，但是有一个建议，生成的网页上面有google统计代码，建议从源码中删除。

**Comment by ssrlive** [comment]
已經去掉了網頁打包，你可以直接修改 html 和 js 文件了。

**Comment by lukemin** [comment]
> 已經去掉了網頁打包，你可以直接修改 html 和 js 文件了。

docker 镜像我也更新了。

**Comment by ssrlive** [comment]
鏡像地址帖一下

**Comment by lukemin** [comment]
> 鏡像地址帖一下

就是readme 里面的地址啊。

**Comment by RuoYear** [comment]
> 已經去掉了網頁打包，你可以直接修改 html 和 js 文件了。


我也注意到这个问题，在重新从docker Hub拉取最新的image后，尝试过以下方法：
1. 通过生成的container，cp整个assets，修改完并复制回去；
2. 和第一步一致， 重新commit后创建新容器；
3. 将整个assets映射到本地目录，将跟domain相关的https修改成http之后，再次重启container；

而在上述操作时，刷新页面和获取的config还是https，但container里面的文件已经是http。只不过重启之后，无论容器内外都被还原回去。
因为对docker不熟悉，但在hub上发现layer中有一句：
`COPY dir:0851b7aebe011c3d25599637b6ba78e26f66c3da4e0a4c14801299702be6f151 in /proxypool-src/assets 
是否有相应的解决方式呢？
